### ISSUE TITLE
Health check 추가

### ISSUE THREAD

**Issue by changjjjjjjj** [DevOcean-2/backend-feed#7]
이슈: 현재 pod 로그를 보면 루트 path가 호출되고 404가 발생함.

원인: aws lb에서 주기적인 서비스 healthcheck를 해서

해결방법: 루트 패스에 헬스체크 추가 (서율님의 코드 베끼기 https://github.com/DevOcean-2/backend-user/blob/d7610a7a8e852902aa246d20a7b4c64a5b8cbbf3/main.py#L72)

**Comment by changjjjjjjj** [comment]
@namkidong98 처리 감사합니다~ 나중을 위한 팁 드리자면 커밋 메세지에 close #{이슈넘버} 혹은 fix #{이슈넘버} 하고 메인 브랜치에 푸시하면 이슈도 같이 닫힙니다!

**Comment by namkidong98** [comment]
@changjjjjjjj 많이 알려주셔서 감사합니다!! 다음번부터는 그렇게 반영하도록 하겠습니다 :)
